# Generated by Django 3.0.8 on 2020-07-10 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='forum.Thread', verbose_name='Tópico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
